-- Initial backend foundation: extensions, profiles table, RLS, storage buckets
-- Generated by Cascade per PRD and backend rules (Unit 1.1 Phase 1.1.1)

-- Extensions
create extension if not exists "uuid-ossp";
create extension if not exists unaccent;
create extension if not exists pg_trgm;

-- Profiles table (linked to auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  locale text default 'ar',
  auto_delete_days int default 0,
  created_at timestamptz default now()
);

-- Enable RLS and own_profile policy
alter table public.profiles enable row level security;

drop policy if exists "own_profile" on public.profiles;
create policy "own_profile" on public.profiles
  for all using (id = auth.uid())
  with check (id = auth.uid());

-- Private storage buckets for audio and exports
insert into storage.buckets (id, name, public)
values ('audio','audio', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('exports','exports', false)
on conflict (id) do nothing;
